using PListLexer
using Base.Test

l, tokens = lex_plist(readstring("test/example.plist"))

@test take!(tokens) == Token(LBRACE)
@test take!(tokens) == Token(IDENT, "Dogs")
@test take!(tokens) == Token(EQUAL)
@test take!(tokens) == Token(LPAREN)
@test take!(tokens) == Token(LBRACE)
@test take!(tokens) == Token(IDENT, "Name")
@test take!(tokens) == Token(EQUAL)
@test take!(tokens) == Token(STRING, "Scooby Doo")
@test take!(tokens) == Token(SEMICOLON)
@test take!(tokens) == Token(IDENT, "Age")
@test take!(tokens) == Token(EQUAL)
@test take!(tokens) == Token(NUMBER, "43")
@test take!(tokens) == Token(SEMICOLON)
@test take!(tokens) == Token(IDENT, "Colors")
@test take!(tokens) == Token(EQUAL)
@test take!(tokens) == Token(LPAREN)
@test take!(tokens) == Token(IDENT, "Brown")
@test take!(tokens) == Token(COMMA)
@test take!(tokens) == Token(IDENT, "Black")
@test take!(tokens) == Token(RPAREN)
@test take!(tokens) == Token(SEMICOLON)
@test take!(tokens) == Token(RBRACE)
@test take!(tokens) == Token(RPAREN)
@test take!(tokens) == Token(SEMICOLON)
@test take!(tokens) == Token(IDENT, "BinaryData")
@test take!(tokens) == Token(EQUAL)
@test take!(tokens) == Token(HEXBINARY, "0fbd771c2735ae")
@test take!(tokens) == Token(SEMICOLON)
@test take!(tokens) == Token(RBRACE)


